In [2]:
import numpy as np

In [4]:
numbers = [float(x) for x in input().split(', ')]

V1 = np.array(numbers)
V2 = np.array([numbers[-2]])
V3 = np.array(numbers[::-1])
V4 = np.array(numbers[0::3])
V5 = np.array(range(len(numbers)))


In [6]:
V1 = np.array([int(x) for x in input().split(', ')])
V2 = np.array([int(x) for x in input().split(', ')])
V3 = V1 + V2
V4 =V1[::2] * (V2[::-1])[::2]

In [13]:
V1 = np.array([int(x) for x in input().split(', ')])
V2 = np.array([int(x) for x in input().split(', ')])

V = np.array([v / V2[-2] for v in V1 if v % V2[-2] == 0])
V

array([1., 2.])

In [14]:
M1 = np.array((
    (1., 2., 3., 0.),
    (4., 5., 6., 0.),
    (0., 1., 1., 6.),
    (7., 8., 9., 0.)
))

In [32]:
np.__version__

'1.26.0'

In [56]:
Z = np.zeros((10,10))
Z[0].itemsize

8

In [46]:
data = input().split()

In [47]:
data

['5']

In [53]:
np.zeros()

array([0., 0., 0., 0., 0.])

In [55]:
isinstance(input().split()[-1], int)

False

In [9]:
Z = np.zeros((10,10))

Z.nbytes

800

In [16]:
np.info(np.array)

array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if ``__array__`` returns a copy, if obj is a nested
    sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly created array w

In [19]:
n = int(input())
x = int(input())

Z = np.zeros(n)
Z[x] = 1

Z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [24]:
n, m = int(input()), int(input())
Z = np.array([x for x in range(n, m + 1)])

Z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [44]:
import numpy as np

Z = np.array((
    (1., 2., 3., 0.),
    (4., 5., 6., 0.),
    (0., 1., 1., 6.),
    (7., 8., 9., 0.)
))
Z = np.flip(Z,1)
Z

array([[0., 3., 2., 1.],
       [0., 6., 5., 4.],
       [6., 1., 1., 0.],
       [0., 9., 8., 7.]])

In [64]:

m, k = 2, 3

Z = np.zeros((m, k))

for i in range(1, m + 1):
    Z[i - 1, :] = [x for x in range(k * (i - 1), k * i)]

Z



array([[0., 1., 2.],
       [3., 4., 5.]])

In [60]:
Z = np.zeros((2, 3))
Z[0, :] = [1, 1, 1]

Z

array([[1., 1., 1.],
       [0., 0., 0.]])

In [65]:
np.info(np.reshape)

Gives a new shape to an array without changing its data.

Parameters
----------
a : array_like
    Array to be reshaped.
newshape : int or tuple of ints
    The new shape should be compatible with the original shape. If
    an integer, then the result will be a 1-D array of that length.
    One shape dimension can be -1. In this case, the value is
    inferred from the length of the array and remaining dimensions.
order : {'C', 'F', 'A'}, optional
    Read the elements of `a` using this index order, and place the
    elements into the reshaped array using this index order.  'C'
    means to read / write the elements using C-like index order,
    with the last axis index changing fastest, back to the first
    axis index changing slowest. 'F' means to read / write the
    elements using Fortran-like index order, with the first index
    changing fastest, and the last index changing slowest. Note that
    the 'C' and 'F' options take no account of the memory layout of
    the underlying 

In [171]:
Z = np.array(
    [
        [[1, 2], [4, 5]],
        [[7, 8], [0, 0]]
    ]
          )
np.nonzero(Z > 3).tolist()

AttributeError: 'tuple' object has no attribute 'tolist'

In [190]:
Z = np.array([[[1, 2],
           [4, 5]],
          [[7, 8],
           [0, 0]]])
list(Z[Z > 3])

[4, 5, 7, 8]

In [196]:
Z = np.eye(3)
Z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [199]:
import numpy as np

np.random.seed(42)

np.reshape(2, 2, 2)


TypeError: order must be str, not int

In [24]:
import numpy as np

n, m = 10, 10
np.random.seed(42)

Z = np.random.random_sample((n, m))

print(np.min(Z))
print(np.max(Z))

0.005522117123602399
0.9868869366005173


In [25]:
import numpy as np

n, m = list(map(int, input().split()))
np.random.seed(42)

Z = np.random.random_sample((n, m))

print(np.mean(Z))


ValueError: invalid literal for int() with base 10: '3,'