In [3]:
import numpy as np

In [4]:
numbers = [float(x) for x in input().split(', ')]

V1 = np.array(numbers)
V2 = np.array([numbers[-2]])
V3 = np.array(numbers[::-1])
V4 = np.array(numbers[0::3])
V5 = np.array(range(len(numbers)))


In [6]:
V1 = np.array([int(x) for x in input().split(', ')])
V2 = np.array([int(x) for x in input().split(', ')])
V3 = V1 + V2
V4 =V1[::2] * (V2[::-1])[::2]

In [13]:
V1 = np.array([int(x) for x in input().split(', ')])
V2 = np.array([int(x) for x in input().split(', ')])

V = np.array([v / V2[-2] for v in V1 if v % V2[-2] == 0])
V

array([1., 2.])

In [14]:
M1 = np.array((
    (1., 2., 3., 0.),
    (4., 5., 6., 0.),
    (0., 1., 1., 6.),
    (7., 8., 9., 0.)
))

In [32]:
np.__version__

'1.26.0'

In [56]:
Z = np.zeros((10,10))
Z[0].itemsize

8

In [46]:
data = input().split()

In [47]:
data

['5']

In [53]:
np.zeros()

array([0., 0., 0., 0., 0.])

In [55]:
isinstance(input().split()[-1], int)

False

In [9]:
Z = np.zeros((10,10))

Z.nbytes

800

In [16]:
np.info(np.array)

array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if ``__array__`` returns a copy, if obj is a nested
    sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly created array w

In [19]:
n = int(input())
x = int(input())

Z = np.zeros(n)
Z[x] = 1

Z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [24]:
n, m = int(input()), int(input())
Z = np.array([x for x in range(n, m + 1)])

Z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [44]:
import numpy as np

Z = np.array((
    (1., 2., 3., 0.),
    (4., 5., 6., 0.),
    (0., 1., 1., 6.),
    (7., 8., 9., 0.)
))
Z = np.flip(Z,1)
Z

array([[0., 3., 2., 1.],
       [0., 6., 5., 4.],
       [6., 1., 1., 0.],
       [0., 9., 8., 7.]])

In [49]:

m, k = 2, 3

Z = np.zeros((m, k))

for i in range(1, m):
    Z[i, :] = [x for x in range(k * (i - 1), k * i)]

Z

TypeError: Cannot interpret '3' as a data type

arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interval includes 